services: 
    persistence:
        image: notebookum-persistence:v1.0.0
        restart: unless-stopped
        # LOAD BALANCER PATTERN
        deploy:
            replicas: 2
        networks:
            notebookum-network:
                aliases:
                    - persistence.universidad.localhost
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.persistence.rule=Host(`persistence.universidad.localhost`)"
            - "traefik.http.routers.persistence.tls=true"
            - "traefik.http.services.persistence.loadbalancer.server.port=5000"
            # CIRCUIT BREAKER PATTERN
            - "traefik.http.middlewares.persistence.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100 || ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10"
            # BULKHEAD PATTERN
            - "traefik.http.middlewares.persistence.inflightreq.amount=10"
        environment:
            - FLASK_ENV=development
            - PORT=5000
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
            - DB_WRITE_HOST=${DB_WRITE_HOST:-mysql-primary}
            - DB_READ_HOST=${DB_READ_HOST:-mysql-replica}
            - DB_PORT=${DB_PORT:-3306}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}

networks:
    notebookum-network:
        external: true
    internal-network:
        internal: true
